# Generated by Django 2.2 on 2019-07-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='imagefun',
            new_name='image',
        ),
    ]
